--- Makefile
+++ Makefile
@@ -28,7 +28,7 @@ space+=
 SRCLIBDIR:= $(subst $(space),\$(space),$(realpath lib))
 
 TARGETS:= stm32/f0 stm32/f1 stm32/f2 stm32/f3 stm32/f4 stm32/f7 \
-	  stm32/l0 stm32/l1 stm32/l4 \
+	  stm32/l0 stm32/l1 stm32/l4 stm32/f150 \
 	  lpc13xx lpc17xx lpc43xx/m4 lpc43xx/m0 lm3s lm4f \
 	  efm32/tg efm32/g efm32/lg efm32/gg \
 	  sam/3a sam/3n sam/3s sam/3u sam/3x \
